import itertools

configfile: "config.json"

localrules: final

include: "serpentine/bio/ngs/rules/bam_processing/sambam.rules"
include: "serpentine/bio/ngs/rules/mapping/bwa.rules"
include: "serpentine/bio/ngs/rules/quality_control/fastqc.rules"
include: "serpentine/bio/ngs/rules/bam_processing/gatk.rules"

def _get_fastq_without_suffix():
    retval = [x.replace('.fastq.gz','') for x in 
              itertools.chain.from_iterable(config['units'].values())]
    return(retval)

rule final:
    input: expand("mapping/human_g1k_v37/samples/{sample}.md.bam",sample=config['samples'].keys()),
           expand("mapping/human_g1k_v37/samples/{sample}.md.recal.bam",sample=config['samples'].keys()),
           expand("{unit}_fastqc.zip", unit = _get_fastq_without_suffix())
    params: batch='-l nodes=1:gpfs'
