configfile: "config.json"

include: "serpentine/bio/ngs/rules/mapping/bwa.rules"

rule final:
    input: expand("mapping/human_g1k_v37/samples/{sample}.bam",sample=config['samples'].keys())
    params: batch='-l nodes=1:gpfs'
