import csv
from serpentine.utils import list_rules

STAR_OUTDIR='bam/{source}/RNA/STAR/'

ss=[]

config['references']={'a':'abc'}
config['reference']='a'
config['gatkVersion']='123'
config['resources']={'dbsnp':'abc'}
config['resources']['knownIndels']='abc'

with open(config['samplesheet'],'r') as csvfile:
    reader = csv.DictReader(csvfile,delimiter='\t')
    for row in reader:
        ss.append(row)


sources = set()
for s in ss:
    sources.add(s['source'])


def source2fastq(wc):
    ret={'fastq':[],
         'rg':[]}
    for row in filter(lambda res:res['source']==wc.source,ss):
        ret['fastq']+=[row['read1'],row['read2']]
        ret['rg']+=[{'ID':row['result_id'],
                     'LB':row['library_id'],
                     'SM':row['source']}]
    return(ret)


include: list_rules()[4]

localrules: final

rule final:
        params: batch="-q ccr -l nodes=1"
        input: expand(STAR_OUTDIR+"/Aligned.sortedByCoord.out.md.bam.bai",source=sources)
        
rule rnaalignment:
    input:  lambda wildcards: source2fastq(wildcards)['fastq']
    output: temp(STAR_OUTDIR+"/Aligned.sortedByCoord.out.bam"),
            STAR_OUTDIR+"/Chimeric.out.junction"
    params:  batch="-q ccr -l nodes=1",
             outdir=STAR_OUTDIR,
             chimJunctionOverhangMin=15,
             chimSegmentMin=15,
             sjdbOverhang=60
    priority: 10
    threads: 32
    version: "2.4.1a"
    run:
        read1 = ','.join(input[0::2])
        read2 = ','.join(input[1::2])
        rg = " , ".join(["ID:{ID} LB:{LB} SM:{SM} PL:Illumina".format(**s) for s in source2fastq(wildcards)['rg']])
        shell("""mkdir -p {params.outdir}
clearscratch
module load STAR/{version}
module load samtools
STAR --genomeDir /data/CCRBioinfo/public/STAR/hg19_gencode14_ov60/ \
        --outFileNamePrefix {params.outdir}/ \
        --readFilesIn {read1} {read2} \
        --runThreadN {threads} \
        --outSAMstrandField intronMotif \
        --outFilterIntronMotifs RemoveNoncanonicalUnannotated \
        --outReadsUnmapped None \
        --chimSegmentMin {params.chimSegmentMin} \
        --chimJunctionOverhangMin {params.chimJunctionOverhangMin} \
        --alignMatesGapMax 200000 \
        --alignIntronMax 200000 \
        --outSAMtype BAM SortedByCoordinate \
        --outTmpDir /scratch/tmp \
        --outSAMattrRGline {rg} \
        --outSAMunmapped Within \
        --chimOutType WithinBam \
        --sjdbOverhang {params.sjdbOverhang} \
        --outFilterMatchNminOverLread 0.1 \
        --outFilterScoreMinOverLread 0.1 \
        --readFilesCommand zcat
""")
